version: "3.9"

services:
  db:
    container_name: postgres_hahn_software
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hahn
      POSTGRES_PASSWORD: hahn123
      POSTGRES_DB: product_management_db
    ports:
      - "5431:5432"
